#!/bin/bash
(ls -a1 | sort -f | awk '{if($1 == "." || $1 == "..") print $1; else { files[NR]=$1 }} END { for (i in files) print files[i] }' | sed 's/$/,/' | tr '\n' ' ' | sed 's/, $/\n/' | sed 's/ /,/g' | sed 's/,,/,/g') | sed 's/,\.,/,.\//g' | sed 's/,..\//,\.\.\//g'

